openapi: 3.0.0
info:
  version: 0.0.1
  title: Test API
  license:
    name: Proprietary

paths:
  /test:
    get:
      tags:
        - Test
      summary: Test test
      description: |
        Just a test
      operationId: testOperation
      parameters:
        - in: query
          name: testQueryParam
          schema:
            type: string
          description: Test query param
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                    test:
                      type: string
        '401':
          $ref: '../components/responses.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../components/responses.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../components/responses.yaml#/components/responses/NotFound'
