openapi: 3.0.0
info:
  version: 0.0.1
  title: Connector Templates Example APIs

paths:  
  /test:
    $ref: 'paths/test.yaml#/paths/~1test'

#components:
  #securitySchemes:
    # bearer currently unsupported by swagger codegen
    #bearerAuth:
    #  type: http
    #  scheme: bearer
    #  bearerFormat: JWT
    #bearerAuth:
    #  type: oauth2
    #  flows:
    #    implicit:
    #      authorizationUrl: /auth/login
    #      refreshUrl: /auth/refresh-tokens
    #      scopes:
    #        manage_own: Manage own stuff

#security:
#  - bearerAuth: []